/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppSettings from './AppSettings';

/**
 * The AuthorizedClients model module.
 * @module model/AuthorizedClients
 * @version 0.0.1
 */
class AuthorizedClients {
    /**
     * Constructs a new <code>AuthorizedClients</code>.
     * @alias module:model/AuthorizedClients
     * @param apps {Array.<module:model/AppSettings>} Applications with access to user measurements for all variables
     * @param individuals {Array.<module:model/AppSettings>} Individuals such as physicians or family members with access to user measurements for all variables
     * @param studies {Array.<module:model/AppSettings>} Studies with access to generally anonymous user measurements for a specific predictor and outcome variable
     */
    constructor(apps, individuals, studies) {

        AuthorizedClients.initialize(this, apps, individuals, studies);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, apps, individuals, studies) {
        obj['apps'] = apps;
        obj['individuals'] = individuals;
        obj['studies'] = studies;
    }

    /**
     * Constructs a <code>AuthorizedClients</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthorizedClients} obj Optional instance to populate.
     * @return {module:model/AuthorizedClients} The populated <code>AuthorizedClients</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthorizedClients();

            if (data.hasOwnProperty('apps')) {
                obj['apps'] = ApiClient.convertToType(data['apps'], [AppSettings]);
            }
            if (data.hasOwnProperty('individuals')) {
                obj['individuals'] = ApiClient.convertToType(data['individuals'], [AppSettings]);
            }
            if (data.hasOwnProperty('studies')) {
                obj['studies'] = ApiClient.convertToType(data['studies'], [AppSettings]);
            }
        }
        return obj;
    }


}

/**
 * Applications with access to user measurements for all variables
 * @member {Array.<module:model/AppSettings>} apps
 */
AuthorizedClients.prototype['apps'] = undefined;

/**
 * Individuals such as physicians or family members with access to user measurements for all variables
 * @member {Array.<module:model/AppSettings>} individuals
 */
AuthorizedClients.prototype['individuals'] = undefined;

/**
 * Studies with access to generally anonymous user measurements for a specific predictor and outcome variable
 * @member {Array.<module:model/AppSettings>} studies
 */
AuthorizedClients.prototype['studies'] = undefined;






export default AuthorizedClients;

