/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExplanationStartTracking from './ExplanationStartTracking';
import Image from './Image';

/**
 * The Explanation model module.
 * @module model/Explanation
 * @version 0.0.1
 */
class Explanation {
    /**
     * Constructs a new <code>Explanation</code>.
     * @alias module:model/Explanation
     * @param description {String} Ex: These factors are most predictive of Overall Mood based on your own data.
     * @param image {module:model/Image}
     * @param ionIcon {String} Ex: ion-ios-person
     * @param startTracking {module:model/ExplanationStartTracking}
     * @param title {String} Ex: Top Predictors of Overall Mood
     */
    constructor(description, image, ionIcon, startTracking, title) {

        Explanation.initialize(this, description, image, ionIcon, startTracking, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, description, image, ionIcon, startTracking, title) {
        obj['description'] = description;
        obj['image'] = image;
        obj['ionIcon'] = ionIcon;
        obj['startTracking'] = startTracking;
        obj['title'] = title;
    }

    /**
     * Constructs a <code>Explanation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Explanation} obj Optional instance to populate.
     * @return {module:model/Explanation} The populated <code>Explanation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Explanation();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = Image.constructFromObject(data['image']);
            }
            if (data.hasOwnProperty('ionIcon')) {
                obj['ionIcon'] = ApiClient.convertToType(data['ionIcon'], 'String');
            }
            if (data.hasOwnProperty('startTracking')) {
                obj['startTracking'] = ExplanationStartTracking.constructFromObject(data['startTracking']);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('html')) {
                obj['html'] = ApiClient.convertToType(data['html'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Ex: These factors are most predictive of Overall Mood based on your own data.
 * @member {String} description
 */
Explanation.prototype['description'] = undefined;

/**
 * @member {module:model/Image} image
 */
Explanation.prototype['image'] = undefined;

/**
 * Ex: ion-ios-person
 * @member {String} ionIcon
 */
Explanation.prototype['ionIcon'] = undefined;

/**
 * @member {module:model/ExplanationStartTracking} startTracking
 */
Explanation.prototype['startTracking'] = undefined;

/**
 * Ex: Top Predictors of Overall Mood
 * @member {String} title
 */
Explanation.prototype['title'] = undefined;

/**
 * Embeddable list of study summaries with explanation at the top
 * @member {String} html
 */
Explanation.prototype['html'] = undefined;






export default Explanation;

