/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExplanationStartTracking from './ExplanationStartTracking';
import Image from './Image';
import Study from './Study';

/**
 * The GetStudiesResponse model module.
 * @module model/GetStudiesResponse
 * @version 0.0.1
 */
class GetStudiesResponse {
    /**
     * Constructs a new <code>GetStudiesResponse</code>.
     * @alias module:model/GetStudiesResponse
     * @param description {String} Ex: These factors are most predictive of Overall Mood based on your own data.
     * @param summary {String} Can be used as title in help info popup
     */
    constructor(description, summary) { 
        
        GetStudiesResponse.initialize(this, description, summary);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, description, summary) { 
        obj['description'] = description;
        obj['summary'] = summary;
    }

    /**
     * Constructs a <code>GetStudiesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetStudiesResponse} obj Optional instance to populate.
     * @return {module:model/GetStudiesResponse} The populated <code>GetStudiesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetStudiesResponse();

            if (data.hasOwnProperty('studies')) {
                obj['studies'] = ApiClient.convertToType(data['studies'], [Study]);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = Image.constructFromObject(data['image']);
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
            }
            if (data.hasOwnProperty('ionIcon')) {
                obj['ionIcon'] = ApiClient.convertToType(data['ionIcon'], 'String');
            }
            if (data.hasOwnProperty('startTracking')) {
                obj['startTracking'] = ExplanationStartTracking.constructFromObject(data['startTracking']);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('html')) {
                obj['html'] = ApiClient.convertToType(data['html'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Study>} studies
 */
GetStudiesResponse.prototype['studies'] = undefined;

/**
 * Ex: These factors are most predictive of Overall Mood based on your own data.
 * @member {String} description
 */
GetStudiesResponse.prototype['description'] = undefined;

/**
 * Can be used as title in help info popup
 * @member {String} summary
 */
GetStudiesResponse.prototype['summary'] = undefined;

/**
 * @member {module:model/Image} image
 */
GetStudiesResponse.prototype['image'] = undefined;

/**
 * Square icon png url
 * @member {String} avatar
 */
GetStudiesResponse.prototype['avatar'] = undefined;

/**
 * Ex: ion-ios-person
 * @member {String} ionIcon
 */
GetStudiesResponse.prototype['ionIcon'] = undefined;

/**
 * @member {module:model/ExplanationStartTracking} startTracking
 */
GetStudiesResponse.prototype['startTracking'] = undefined;

/**
 * Ex: Top Predictors of Overall Mood
 * @member {String} title
 */
GetStudiesResponse.prototype['title'] = undefined;

/**
 * Embeddable list of study summaries with explanation at the top
 * @member {String} html
 */
GetStudiesResponse.prototype['html'] = undefined;






export default GetStudiesResponse;

