/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MeasurementItem model module.
 * @module model/MeasurementItem
 * @version 0.0.1
 */
class MeasurementItem {
    /**
     * Constructs a new <code>MeasurementItem</code>.
     * @alias module:model/MeasurementItem
     * @param timestamp {Number} Timestamp for the measurement event in epoch time (unixtime)
     * @param value {Number} Measurement value
     */
    constructor(timestamp, value) {

        MeasurementItem.initialize(this, timestamp, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, timestamp, value) {
        obj['timestamp'] = timestamp;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>MeasurementItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MeasurementItem} obj Optional instance to populate.
     * @return {module:model/MeasurementItem} The populated <code>MeasurementItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MeasurementItem();

            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Optional note to include with the measurement
 * @member {String} note
 */
MeasurementItem.prototype['note'] = undefined;

/**
 * Timestamp for the measurement event in epoch time (unixtime)
 * @member {Number} timestamp
 */
MeasurementItem.prototype['timestamp'] = undefined;

/**
 * Measurement value
 * @member {Number} value
 */
MeasurementItem.prototype['value'] = undefined;






export default MeasurementItem;

