/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ShareInvitationBody model module.
 * @module model/ShareInvitationBody
 * @version 0.0.1
 */
class ShareInvitationBody {
    /**
     * Constructs a new <code>ShareInvitationBody</code>.
     * @alias module:model/ShareInvitationBody
     * @param emailAddress {String} Enter the email address of the friend, family member, or health-care provider that you would like to give access to your measurements
     */
    constructor(emailAddress) { 
        
        ShareInvitationBody.initialize(this, emailAddress);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, emailAddress) { 
        obj['emailAddress'] = emailAddress;
    }

    /**
     * Constructs a <code>ShareInvitationBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShareInvitationBody} obj Optional instance to populate.
     * @return {module:model/ShareInvitationBody} The populated <code>ShareInvitationBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShareInvitationBody();

            if (data.hasOwnProperty('emailAddress')) {
                obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('emailSubject')) {
                obj['emailSubject'] = ApiClient.convertToType(data['emailSubject'], 'String');
            }
            if (data.hasOwnProperty('emailBody')) {
                obj['emailBody'] = ApiClient.convertToType(data['emailBody'], 'String');
            }
            if (data.hasOwnProperty('scopes')) {
                obj['scopes'] = ApiClient.convertToType(data['scopes'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Enter the email address of the friend, family member, or health-care provider that you would like to give access to your measurements
 * @member {String} emailAddress
 */
ShareInvitationBody.prototype['emailAddress'] = undefined;

/**
 * Name of the individual that the user wishes to have access to their measurements
 * @member {String} name
 */
ShareInvitationBody.prototype['name'] = undefined;

/**
 * Ex: I would like to share my measurements with you!
 * @member {String} emailSubject
 */
ShareInvitationBody.prototype['emailSubject'] = undefined;

/**
 * Ex: I would like to share my data with you so you can help me identify find discover hidden causes of and new treatments for my illness.
 * @member {String} emailBody
 */
ShareInvitationBody.prototype['emailBody'] = undefined;

/**
 * Space separated list of scopes to grant to the recipient (i.e. readmeasurements, writemeasurements, measurements:read
 * @member {String} scopes
 */
ShareInvitationBody.prototype['scopes'] = undefined;






export default ShareInvitationBody;

