/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Card from './Card';
import Error from './Error';
import Image from './Image';
import User from './User';

/**
 * The UsersResponse model module.
 * @module model/UsersResponse
 * @version 0.0.1
 */
class UsersResponse {
    /**
     * Constructs a new <code>UsersResponse</code>.
     * @alias module:model/UsersResponse
     * @param users {Array.<module:model/User>}
     */
    constructor(users) {

        UsersResponse.initialize(this, users);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, users) {
        obj['users'] = users;
    }

    /**
     * Constructs a <code>UsersResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersResponse} obj Optional instance to populate.
     * @return {module:model/UsersResponse} The populated <code>UsersResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersResponse();

            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], [User]);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [Error]);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = Image.constructFromObject(data['image']);
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
            }
            if (data.hasOwnProperty('ionIcon')) {
                obj['ionIcon'] = ApiClient.convertToType(data['ionIcon'], 'String');
            }
            if (data.hasOwnProperty('html')) {
                obj['html'] = ApiClient.convertToType(data['html'], 'String');
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
            if (data.hasOwnProperty('card')) {
                obj['card'] = Card.constructFromObject(data['card']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/User>} users
 */
UsersResponse.prototype['users'] = undefined;

/**
 * Users who granted access to their data
 * @member {String} description
 */
UsersResponse.prototype['description'] = undefined;

/**
 * Users who granted access to their data
 * @member {String} summary
 */
UsersResponse.prototype['summary'] = undefined;

/**
 * Array of error objects with message property
 * @member {Array.<module:model/Error>} errors
 */
UsersResponse.prototype['errors'] = undefined;

/**
 * ex. OK or ERROR
 * @member {String} status
 */
UsersResponse.prototype['status'] = undefined;

/**
 * true or false
 * @member {Boolean} success
 */
UsersResponse.prototype['success'] = undefined;

/**
 * Response code such as 200
 * @member {Number} code
 */
UsersResponse.prototype['code'] = undefined;

/**
 * @member {module:model/Image} image
 */
UsersResponse.prototype['image'] = undefined;

/**
 * Square icon png url
 * @member {String} avatar
 */
UsersResponse.prototype['avatar'] = undefined;

/**
 * Ex: ion-ios-person
 * @member {String} ionIcon
 */
UsersResponse.prototype['ionIcon'] = undefined;

/**
 * Users who granted access to their data
 * @member {String} html
 */
UsersResponse.prototype['html'] = undefined;

/**
 * A super neat url you might want to share with your users!
 * @member {String} link
 */
UsersResponse.prototype['link'] = undefined;

/**
 * @member {module:model/Card} card
 */
UsersResponse.prototype['card'] = undefined;






export default UsersResponse;

