/**
 * CureDAO Unified Health API
 * A community-owned platform for crowdsourced clinical research
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AppSettings from './model/AppSettings';
import AppSettingsResponse from './model/AppSettingsResponse';
import AuthorizedClients from './model/AuthorizedClients';
import Button from './model/Button';
import Card from './model/Card';
import Chart from './model/Chart';
import CommonResponse from './model/CommonResponse';
import ConnectInstructions from './model/ConnectInstructions';
import ConversionStep from './model/ConversionStep';
import Correlation from './model/Correlation';
import DataSource from './model/DataSource';
import DeviceToken from './model/DeviceToken';
import Error from './model/Error';
import Explanation from './model/Explanation';
import ExplanationStartTracking from './model/ExplanationStartTracking';
import FeedResponse from './model/FeedResponse';
import GetConnectorsResponse from './model/GetConnectorsResponse';
import GetCorrelationsDataResponse from './model/GetCorrelationsDataResponse';
import GetCorrelationsResponse from './model/GetCorrelationsResponse';
import GetSharesResponse from './model/GetSharesResponse';
import GetStudiesResponse from './model/GetStudiesResponse';
import GetTrackingReminderNotificationsResponse from './model/GetTrackingReminderNotificationsResponse';
import Image from './model/Image';
import InputField from './model/InputField';
import JsonErrorResponse from './model/JsonErrorResponse';
import Measurement from './model/Measurement';
import MeasurementItem from './model/MeasurementItem';
import MeasurementSet from './model/MeasurementSet';
import MeasurementUpdate from './model/MeasurementUpdate';
import Pair from './model/Pair';
import ParticipantInstruction from './model/ParticipantInstruction';
import PostMeasurementsDataResponse from './model/PostMeasurementsDataResponse';
import PostMeasurementsResponse from './model/PostMeasurementsResponse';
import PostStudyCreateResponse from './model/PostStudyCreateResponse';
import PostStudyPublishResponse from './model/PostStudyPublishResponse';
import PostTrackingRemindersDataResponse from './model/PostTrackingRemindersDataResponse';
import PostTrackingRemindersResponse from './model/PostTrackingRemindersResponse';
import PostUserSettingsDataResponse from './model/PostUserSettingsDataResponse';
import PostUserSettingsResponse from './model/PostUserSettingsResponse';
import ShareInvitationBody from './model/ShareInvitationBody';
import Study from './model/Study';
import StudyCharts from './model/StudyCharts';
import StudyCreationBody from './model/StudyCreationBody';
import StudyHtml from './model/StudyHtml';
import StudyImages from './model/StudyImages';
import StudyJoinResponse from './model/StudyJoinResponse';
import StudyLinks from './model/StudyLinks';
import StudySharing from './model/StudySharing';
import StudyText from './model/StudyText';
import StudyVotes from './model/StudyVotes';
import TrackingReminder from './model/TrackingReminder';
import TrackingReminderNotification from './model/TrackingReminderNotification';
import TrackingReminderNotificationAction from './model/TrackingReminderNotificationAction';
import TrackingReminderNotificationPost from './model/TrackingReminderNotificationPost';
import TrackingReminderNotificationTrackAllAction from './model/TrackingReminderNotificationTrackAllAction';
import Unit from './model/Unit';
import UnitCategory from './model/UnitCategory';
import User from './model/User';
import UserTag from './model/UserTag';
import UserVariableDelete from './model/UserVariableDelete';
import UsersResponse from './model/UsersResponse';
import Variable from './model/Variable';
import VariableCategory from './model/VariableCategory';
import VariableCharts from './model/VariableCharts';
import Vote from './model/Vote';
import AnalyticsApi from './api/AnalyticsApi';
import AppSettingsApi from './api/AppSettingsApi';
import AuthenticationApi from './api/AuthenticationApi';
import ConnectorsApi from './api/ConnectorsApi';
import FeedApi from './api/FeedApi';
import MeasurementsApi from './api/MeasurementsApi';
import NotificationsApi from './api/NotificationsApi';
import RemindersApi from './api/RemindersApi';
import SharesApi from './api/SharesApi';
import StudiesApi from './api/StudiesApi';
import UnitsApi from './api/UnitsApi';
import UserApi from './api/UserApi';
import VariablesApi from './api/VariablesApi';


/**
* A community-owned platform for crowdsourcing clincal research.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CureDaoApi = require('index'); // See note below*.
* var xxxSvc = new CureDaoApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CureDaoApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CureDaoApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CureDaoApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AppSettings model constructor.
     * @property {module:model/AppSettings}
     */
    AppSettings,

    /**
     * The AppSettingsResponse model constructor.
     * @property {module:model/AppSettingsResponse}
     */
    AppSettingsResponse,

    /**
     * The AuthorizedClients model constructor.
     * @property {module:model/AuthorizedClients}
     */
    AuthorizedClients,

    /**
     * The Button model constructor.
     * @property {module:model/Button}
     */
    Button,

    /**
     * The Card model constructor.
     * @property {module:model/Card}
     */
    Card,

    /**
     * The Chart model constructor.
     * @property {module:model/Chart}
     */
    Chart,

    /**
     * The CommonResponse model constructor.
     * @property {module:model/CommonResponse}
     */
    CommonResponse,

    /**
     * The ConnectInstructions model constructor.
     * @property {module:model/ConnectInstructions}
     */
    ConnectInstructions,

    /**
     * The ConversionStep model constructor.
     * @property {module:model/ConversionStep}
     */
    ConversionStep,

    /**
     * The Correlation model constructor.
     * @property {module:model/Correlation}
     */
    Correlation,

    /**
     * The DataSource model constructor.
     * @property {module:model/DataSource}
     */
    DataSource,

    /**
     * The DeviceToken model constructor.
     * @property {module:model/DeviceToken}
     */
    DeviceToken,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Explanation model constructor.
     * @property {module:model/Explanation}
     */
    Explanation,

    /**
     * The ExplanationStartTracking model constructor.
     * @property {module:model/ExplanationStartTracking}
     */
    ExplanationStartTracking,

    /**
     * The FeedResponse model constructor.
     * @property {module:model/FeedResponse}
     */
    FeedResponse,

    /**
     * The GetConnectorsResponse model constructor.
     * @property {module:model/GetConnectorsResponse}
     */
    GetConnectorsResponse,

    /**
     * The GetCorrelationsDataResponse model constructor.
     * @property {module:model/GetCorrelationsDataResponse}
     */
    GetCorrelationsDataResponse,

    /**
     * The GetCorrelationsResponse model constructor.
     * @property {module:model/GetCorrelationsResponse}
     */
    GetCorrelationsResponse,

    /**
     * The GetSharesResponse model constructor.
     * @property {module:model/GetSharesResponse}
     */
    GetSharesResponse,

    /**
     * The GetStudiesResponse model constructor.
     * @property {module:model/GetStudiesResponse}
     */
    GetStudiesResponse,

    /**
     * The GetTrackingReminderNotificationsResponse model constructor.
     * @property {module:model/GetTrackingReminderNotificationsResponse}
     */
    GetTrackingReminderNotificationsResponse,

    /**
     * The Image model constructor.
     * @property {module:model/Image}
     */
    Image,

    /**
     * The InputField model constructor.
     * @property {module:model/InputField}
     */
    InputField,

    /**
     * The JsonErrorResponse model constructor.
     * @property {module:model/JsonErrorResponse}
     */
    JsonErrorResponse,

    /**
     * The Measurement model constructor.
     * @property {module:model/Measurement}
     */
    Measurement,

    /**
     * The MeasurementItem model constructor.
     * @property {module:model/MeasurementItem}
     */
    MeasurementItem,

    /**
     * The MeasurementSet model constructor.
     * @property {module:model/MeasurementSet}
     */
    MeasurementSet,

    /**
     * The MeasurementUpdate model constructor.
     * @property {module:model/MeasurementUpdate}
     */
    MeasurementUpdate,

    /**
     * The Pair model constructor.
     * @property {module:model/Pair}
     */
    Pair,

    /**
     * The ParticipantInstruction model constructor.
     * @property {module:model/ParticipantInstruction}
     */
    ParticipantInstruction,

    /**
     * The PostMeasurementsDataResponse model constructor.
     * @property {module:model/PostMeasurementsDataResponse}
     */
    PostMeasurementsDataResponse,

    /**
     * The PostMeasurementsResponse model constructor.
     * @property {module:model/PostMeasurementsResponse}
     */
    PostMeasurementsResponse,

    /**
     * The PostStudyCreateResponse model constructor.
     * @property {module:model/PostStudyCreateResponse}
     */
    PostStudyCreateResponse,

    /**
     * The PostStudyPublishResponse model constructor.
     * @property {module:model/PostStudyPublishResponse}
     */
    PostStudyPublishResponse,

    /**
     * The PostTrackingRemindersDataResponse model constructor.
     * @property {module:model/PostTrackingRemindersDataResponse}
     */
    PostTrackingRemindersDataResponse,

    /**
     * The PostTrackingRemindersResponse model constructor.
     * @property {module:model/PostTrackingRemindersResponse}
     */
    PostTrackingRemindersResponse,

    /**
     * The PostUserSettingsDataResponse model constructor.
     * @property {module:model/PostUserSettingsDataResponse}
     */
    PostUserSettingsDataResponse,

    /**
     * The PostUserSettingsResponse model constructor.
     * @property {module:model/PostUserSettingsResponse}
     */
    PostUserSettingsResponse,

    /**
     * The ShareInvitationBody model constructor.
     * @property {module:model/ShareInvitationBody}
     */
    ShareInvitationBody,

    /**
     * The Study model constructor.
     * @property {module:model/Study}
     */
    Study,

    /**
     * The StudyCharts model constructor.
     * @property {module:model/StudyCharts}
     */
    StudyCharts,

    /**
     * The StudyCreationBody model constructor.
     * @property {module:model/StudyCreationBody}
     */
    StudyCreationBody,

    /**
     * The StudyHtml model constructor.
     * @property {module:model/StudyHtml}
     */
    StudyHtml,

    /**
     * The StudyImages model constructor.
     * @property {module:model/StudyImages}
     */
    StudyImages,

    /**
     * The StudyJoinResponse model constructor.
     * @property {module:model/StudyJoinResponse}
     */
    StudyJoinResponse,

    /**
     * The StudyLinks model constructor.
     * @property {module:model/StudyLinks}
     */
    StudyLinks,

    /**
     * The StudySharing model constructor.
     * @property {module:model/StudySharing}
     */
    StudySharing,

    /**
     * The StudyText model constructor.
     * @property {module:model/StudyText}
     */
    StudyText,

    /**
     * The StudyVotes model constructor.
     * @property {module:model/StudyVotes}
     */
    StudyVotes,

    /**
     * The TrackingReminder model constructor.
     * @property {module:model/TrackingReminder}
     */
    TrackingReminder,

    /**
     * The TrackingReminderNotification model constructor.
     * @property {module:model/TrackingReminderNotification}
     */
    TrackingReminderNotification,

    /**
     * The TrackingReminderNotificationAction model constructor.
     * @property {module:model/TrackingReminderNotificationAction}
     */
    TrackingReminderNotificationAction,

    /**
     * The TrackingReminderNotificationPost model constructor.
     * @property {module:model/TrackingReminderNotificationPost}
     */
    TrackingReminderNotificationPost,

    /**
     * The TrackingReminderNotificationTrackAllAction model constructor.
     * @property {module:model/TrackingReminderNotificationTrackAllAction}
     */
    TrackingReminderNotificationTrackAllAction,

    /**
     * The Unit model constructor.
     * @property {module:model/Unit}
     */
    Unit,

    /**
     * The UnitCategory model constructor.
     * @property {module:model/UnitCategory}
     */
    UnitCategory,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserTag model constructor.
     * @property {module:model/UserTag}
     */
    UserTag,

    /**
     * The UserVariableDelete model constructor.
     * @property {module:model/UserVariableDelete}
     */
    UserVariableDelete,

    /**
     * The UsersResponse model constructor.
     * @property {module:model/UsersResponse}
     */
    UsersResponse,

    /**
     * The Variable model constructor.
     * @property {module:model/Variable}
     */
    Variable,

    /**
     * The VariableCategory model constructor.
     * @property {module:model/VariableCategory}
     */
    VariableCategory,

    /**
     * The VariableCharts model constructor.
     * @property {module:model/VariableCharts}
     */
    VariableCharts,

    /**
     * The Vote model constructor.
     * @property {module:model/Vote}
     */
    Vote,

    /**
    * The AnalyticsApi service constructor.
    * @property {module:api/AnalyticsApi}
    */
    AnalyticsApi,

    /**
    * The AppSettingsApi service constructor.
    * @property {module:api/AppSettingsApi}
    */
    AppSettingsApi,

    /**
    * The AuthenticationApi service constructor.
    * @property {module:api/AuthenticationApi}
    */
    AuthenticationApi,

    /**
    * The ConnectorsApi service constructor.
    * @property {module:api/ConnectorsApi}
    */
    ConnectorsApi,

    /**
    * The FeedApi service constructor.
    * @property {module:api/FeedApi}
    */
    FeedApi,

    /**
    * The MeasurementsApi service constructor.
    * @property {module:api/MeasurementsApi}
    */
    MeasurementsApi,

    /**
    * The NotificationsApi service constructor.
    * @property {module:api/NotificationsApi}
    */
    NotificationsApi,

    /**
    * The RemindersApi service constructor.
    * @property {module:api/RemindersApi}
    */
    RemindersApi,

    /**
    * The SharesApi service constructor.
    * @property {module:api/SharesApi}
    */
    SharesApi,

    /**
    * The StudiesApi service constructor.
    * @property {module:api/StudiesApi}
    */
    StudiesApi,

    /**
    * The UnitsApi service constructor.
    * @property {module:api/UnitsApi}
    */
    UnitsApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi,

    /**
    * The VariablesApi service constructor.
    * @property {module:api/VariablesApi}
    */
    VariablesApi
};
